export const visCols = [
  "id",
  "image",
  "current_price",
  "market_cap",
  "market_cap_rank",
  "total_volume",
  "high_24h",
  "low_24h",
  "price_change_24h",
  "price_change_percentage_24h",
  "market_cap_change_24h",
  "market_cap_change_percentage_24h",
  "circulating_supply",
  "max_supply",
  "ath",
  "ath_change_percentage",
  "ath_date",
  "atl",
  "atl_change_percentage",
  "atl_date",
  "last_updated",
]

export const sortableCols = ["market_cap", "total_volume", "id"]

export const colTitles = {
  id: "Название",
  image: "Изображение",
  current_price: "Текущая цена USD",
  market_cap: "Рыночная капитализация USD",
  market_cap_rank: "Ранг по капитализации",
  total_volume: "Общий объем торгов USD",
  high_24h: "Максимум за 24ч USD",
  low_24h: "Минимум за 24ч USD",
  price_change_24h: "Изменение цены (24ч) USD",
  price_change_percentage_24h: "Изменение цены % (24ч)",
  market_cap_change_24h: "Изменение капитализации (24ч) USD",
  market_cap_change_percentage_24h: "Изменение капитализации % (24ч)",
  circulating_supply: "Оборотное предложение USD",
  max_supply: "Максимальное предложение USD",
  ath: "Исторический максимум USD",
  ath_change_percentage: "Изменение от максимума %",
  ath_date: "Дата максимума",
  atl: "Исторический минимум USD",
  atl_change_percentage: "Изменение от минимума %",
  atl_date: "Дата минимума",
  last_updated: "Последнее обновление",
}

export const walletTableTitles = {
  id: "Название",
  image: "Изображение",
  onBalance: "На счету",
  spendSum: "Сумма затрат",
  profit: "Прибыль USDT",
  current_price: "Текущая цена USD",
  high_24h: "Максимум за 24ч USD",
  low_24h: "Минимум за 24ч USD",
  price_change_24h: "Изменение цены (24ч) USD",
  price_change_percentage_24h: "Изменение цены % (24ч)",
  last_updated: "Последнее обновление",
}

export const visColsWallet = [
  "id",
  "image",
  "onBalance",
  "spendSum",
  "profit",
  "current_price",
  "high_24h",
  "low_24h",
  "price_change_24h",
  "market_cap_change_percentage_24h",
  "last_updated",
]
